# Generated by Django 5.0.1 on 2024-02-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=255)),
                ('market_value', models.FloatField()),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('land_size', models.FloatField()),
                ('building_size', models.FloatField()),
                ('compound_size', models.FloatField()),
                ('construction_value', models.IntegerField()),
                ('lga', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('tax_payable', models.FloatField(default=0.0)),
                ('payment', models.CharField(max_length=255)),
                ('tax_rate', models.FloatField()),
                ('luc', models.FloatField()),
                ('land_value', models.FloatField()),
                ('building_value', models.FloatField()),
                ('property_image', models.ImageField(upload_to='property_images/')),
                ('airs', models.ImageField(upload_to='airs_images/')),
                ('relief_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('charge_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
