# Generated by Django 5.0.1 on 2024-02-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='building_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='luc',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tax_rate',
        ),
    ]
