# Generated by Django 5.0.1 on 2024-02-10 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='lga',
            new_name='LGA',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='payment',
            new_name='status',
        ),
        
        migrations.RemoveField(
            model_name='property',
            name='building_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='luc',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='building_size',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='charge_rate',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='compound_size',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='market_value',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='relief_rate',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_payable',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=5, max_digits=15)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('payment_option', models.CharField(default='null', max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_tax.property')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property_tax.payment')),
            ],
        ),
    ]
