# Generated by Django 5.0.1 on 2024-02-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0002_remove_property_building_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='depreciation_rate',
            field=models.FloatField(),
        ),
    ]
