# Generated by Django 5.0.1 on 2024-02-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0003_alter_property_depreciation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tax_payable',
            field=models.FloatField(default='null'),
        ),
    ]
