# Generated by Django 5.0.1 on 2024-02-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0005_alter_property_tax_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='compound_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='market_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_payable',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
