# Generated by Django 5.0.1 on 2024-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0006_alter_property_building_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_size',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='charge_rate',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='compound_size',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='market_value',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='relief_rate',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_payable',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
