# Generated by Django 5.0.1 on 2024-02-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0007_alter_property_building_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='airs',
        ),
    ]
