# Generated by Django 5.0.1 on 2024-02-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0008_remove_property_airs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
