# Generated by Django 5.0.1 on 2024-02-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0009_remove_property_id_property_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
