# Generated by Django 5.0.1 on 2024-02-08 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0011_rename_lga_property_lga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='payment',
            new_name='status',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=5, max_digits=15)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_tax.property')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property_tax.payment')),
            ],
        ),
    ]
