# Generated by Django 5.0.1 on 2024-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tax', '0012_rename_payment_property_status_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
